# Generated by Django 4.1 on 2022-08-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20, verbose_name='Nome de Usuário')),
                ('senha', models.CharField(max_length=20, verbose_name='Senha')),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=20, verbose_name='Setor')),
                ('solicitante', models.CharField(max_length=20, verbose_name='Solicitante')),
                ('data_solicitacao', models.DateField(verbose_name='Data da Solicitação')),
                ('data_agenda', models.DateField(verbose_name='Data de agendamento')),
                ('chamado_GLPI', models.CharField(max_length=10, verbose_name='Chamado GLPI')),
                ('hora_inicio', models.TimeField(verbose_name='Inicio da Reserva')),
                ('hora_final', models.TimeField(verbose_name='Final da Reserva')),
                ('observacao', models.CharField(max_length=100, verbose_name='Observação')),
            ],
        ),
    ]
